### ISSUE TITLE
Support adding persistent volume to navigator-apiserver etcd container

### ISSUE THREAD

**Issue by wallrj** [jetstack/navigator#135]
/kind bug

* I had a cluster with Navigator databases running.
* I scaled the cluster down to 0 nodes.
* When I scale the cluster back up, the Navigator resources are all missing.
* And the StatefulSets and services that Navigator controller created are all gone too.

**Comment by munnerz** [comment]
I guess you deleted the navigator-apiserver pod somewhere in amongst the above? ^

This is expected right now as we don't attach a persistent volume for navigator. If you want persistent data, you will need to deploy a standalone etcd.
