### ISSUE TITLE
E2E TEST FAILURE: Elasticsearch pilot did not update the document count

### ISSUE THREAD

**Issue by wallrj** [jetstack/navigator#220]
It looks to me like the Kubernetes couldn't create a PV for the ES pod.

 * https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_navigator/209/navigator-e2e-v1-8/623/

Seen in #209 

```
==== START logs for container elasticsearch of pod test-elasticsearchcluster-1516805618-18656/es-test-mixed-0 ====
failed to get container status {"docker" "6265b4b7de6ce82b9f752e0e80aa493c67b374018274312307caae4ed5121638"}: rpc error: code = Unknown desc = Error: No such container: 6265b4b7de6ce82b9f752e0e80aa493c67b374018274312307caae4ed5121638==== END logs for container elasticsearch of pod test-elasticsearchcluster-1516805618-18656/es-test-mixed-0 ====
Cluster info dumped to standard output

```
 * [cluster-info dump](https://00e9e64bacce027e18ef172f22a0e40328bc8cfcc062debb60-apidata.googleusercontent.com/download/storage/v1/b/jetstack-logs/o/pr-logs%2Fpull%2Fjetstack_navigator%2F209%2Fnavigator-e2e-v1-8%2F623%2Fartifacts%2Ftest-elasticsearchcluster-1516805618-18656%2Fdump.txt?qk=AD5uMEuc8wtk7YDG86oW1vBtrVHp_fcYY8RhE5pdSIqBFcD5HIqJK0ZNrhoWa7bOt04KIjx8Qf4ISvX_Oz6tvL2RkCVgGGoaGOD6bgFxqSBhVWoWOPh5YI1CuLzsoJw-Z7EK5x7nFE0Rc8NLEfLutTXZG4df4_5DTMoWeczg9swf4QailFhHo2qOenECoSdIz6XeUvKZNiOhZ1AKk7ows2dwpKV_Q4IefQhG4kDj9RY8gD2XYIQ6APF1g7O8FztiDTuqpzopBt7Z3gEXLNBevorSXQv2Rzep-gElzknXQWEsmHAkOgp5DIbmM-bZAS8I4WVLh-647UrWrJd0YZl92PRkyiwZhabWJzGaaxx-70a2araOV8-nJoqBkYih10AmGV8lfi05R6aWOSuzB4QVQCxWIEWXs75agrbFrig6Lag9pppO9ISZETL9Yc1_R-hiTcS5ChVyBOHe_OQbXImmMckazeWQCIduBIRnDW0MkZNDcKSkGVmmRyNequgxsaxTUcDIO2I9cOkLp2Jak7jB5CyP2-PlFSMetPeiQaMvT5zdrWI_hPvNA092aNoHjT2ra5LAubnEdDXK9Ws5qcIS90NHIQlXoTpEW1L9BxnZSGCUdX4CWzlOw4L3oemznXQ5vAq2fCTrTGNc3nH3j3M2zLk2Ut-2pT01WcWKmimpN8uIE2O0hjStLGM3F4nH0NTf5le2sQvbGKNIQ3DBy4r243wBOMNHH2fHMDxPKnuXRDANCBVmNVW8UBj8ouXAx44N16InQfw0Jx5oUq91Tw3mzaF-9rvzMT7SxQUYSpPIn2DO6g2TcgaWEQUPPAIjAPFx9tpJgc7jHQ794csrfCR7QMqKkDtp2FDYDWW49mjcWY9bS1-M6DRfd0KZzQPAQUsZRVQwTJbHdJEnPNua3SiW-cccFR1geBTZjg)

```
Jan 24 15:04:30 13471c29-0113-11e8-9b46-0a580a1c1f0d kubelet[3165]: E0124 15:04:30.295137    3165 kubelet.go:1628] Unable to mount volumes for pod "es-test-mixed-0_test-elasticsearchcluster-1516805618-18656(977edf87-0117-11e8-8830-525400dcf159)": timeout expired waiting for volumes to attach/mount for pod "test-elasticsearchcluster-1516805618-18656"/"es-test-mixed-0". list of unattached/unmounted volumes=[shared config elasticsearch-data es-test-token-d6xl6]; skipping pod
Jan 24 15:04:30 13471c29-0113-11e8-9b46-0a580a1c1f0d kubelet[3165]: E0124 15:04:30.295671    3165 pod_workers.go:182] Error syncing pod 977edf87-0117-11e8-8830-525400dcf159 ("es-test-mixed-0_test-elasticsearchcluster-1516805618-18656(977edf87-0117-11e8-8830-525400dcf159)"), skipping: timeout expired waiting for volumes to attach/mount for pod "test-elasticsearchcluster-1516805618-18656"/"es-test-mixed-0". list of unattached/unmounted volumes=[shared config elasticsearch-data es-test-token-d6xl6]
Jan 24 15:04:31 13471c29-0113-11e8-9b46-0a580a1c1f0d kubelet[3165]: I0124 15:04:31.285622    3165 kuberuntime_manager.go:500] Container {Name:elasticsearch Image:docker.elastic.co/elasticsearch/elasticsearch:5.6.2 Command:[/shared/pilot] Args:[--v=4 --logtostderr --pilot-name=$(POD_NAME) --pilot-namespace=$(POD_NAMESPACE) --elasticsearch-master-url=$(CLUSTER_URL) --elasticsearch-roles=$(ROLES) --elasticsearch-plugins=$(PLUGINS) --leader-election-config-map=$(LEADER_ELECTION_CONFIG_MAP)] WorkingDir: Ports:[{Name:transport HostPort:0 ContainerPort:9300 Protocol:TCP HostIP:} {Name:http HostPort:0 ContainerPort:9200 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:DISCOVERY_URL Value:es-test-discovery ValueFrom:nil} {Name:ROLES Value:master,ingest,data ValueFrom:nil} {Name:PLUGINS Value: ValueFrom:nil} {Name:LEADER_ELECTION_CONFIG_MAP Value:elastic-test-leaderelection ValueFrom:nil} {Name:CLUSTER_URL Value:http://es-test:9200 ValueFrom:nil} {Name:POD_NAME Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {Name:POD_NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:500 scale:-3} d:{Dec:<nil>} s:500m Format:DecimalSI} memory:{i:{value:2147483648 scale:0} d:{Dec:<nil>} s:2Gi Format:BinarySI}]} VolumeMounts:[{Name:elasticsearch-data ReadOnly:false MountPath:/usr/share/elasticsearch/data SubPath: MountPropagation:<nil>} {Name:shared ReadOnly:true MountPath:/shared SubPath: MountPropagation:<nil>} {Name:config ReadOnly:false MountPath:/etc/pilot/elasticsearch/config SubPath: MountPropagation:<nil>} {Name:es-test-token-d6xl6 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:12000,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSe
Jan 24 15:04:31 13471c29-0113-11e8-9b46-0a580a1c1f0d kubelet[3165]: conds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:12001,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:30,TimeoutSeconds:3,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[IPC_LOCK],Drop:[],},Privileged:nil,SELinuxOptions:nil,RunAsUser:*1000,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

```
* [minikube logs](https://00e9e64bac47893783070f57c1dbea5daec8ec8b8b22dae6ef-apidata.googleusercontent.com/download/storage/v1/b/jetstack-logs/o/pr-logs%2Fpull%2Fjetstack_navigator%2F209%2Fnavigator-e2e-v1-8%2F623%2Fartifacts%2Fminikube-logs.txt?qk=AD5uMEtACO9EFxrSl1oU9A0pRwOFLjHmRpkmm1m_1aB7DRbcCaMVvcp_B3dJnF1LuBIpeWUJKYMfapQDi_rBOApzikedPFN6Y8Lict-0GVIn3RMSO5Q5ihNHyyYKXcHkwWOfd6vQZSUy-UQ5iNLNoHNznSyg7fbR89e47asWObuR632qsBmvi2NG24P0a9WY0mLFVobxToJb_8fbWm5NmSjB15XOX6-I6E4PIk8D_Q1gLa6Aqkzc0I_ljoEYs5Yupf7_01noAcGWYikNOa8KSaV66IgJZ_dJ3aUuoFV5ZQpw47LP8odillpfUlPpno4x8s3kKH19aptJnliDBxx7NZvCuKWUug6noivOm00hOJykQ0m4neFJDmeSIFp6iVknQnBl06BApeB9iQzCrEpVXk6zyhz0KX_dppsf3H047362UU6W4DdRIpsDKEeUBCUvzTCmLCrNihjAg3vzIc-3HYA_7VE6sVfShisMWIvmY3GMb2vgc4aCPeXvuc-RKZIPj281xAItYpd-6F3T-KVAoqxP-x4iBtqizlntQkFGluS2MdeUCazzBHy4LW_JcsqzOin5zDoh62UKLJ5BYquMiy9w14th8Gvdval2MiqdPW3_8XnNeHsrtYvzvwkLaZ4GqKAMLk9awoKTnJ5oVU7KMmusI5vo9qgCK3tjlkmT3j5x5VIENEJvoLHK-3Avi7NO0ehWgLgw7LAZlxTDuWNVD7ck0Tb1m6fjDkAGdJvJaQm9jLYiZYzD31fw74_gf1Sa7x8HdK6B0au7bzrB06NO6arO5-ljUu73Q-fuLNnUhF7iIvcraZ23q-rg31b4MbKyxPhJzd3I9O6cRPQ7hU_rgAfnSubMeHVpdQ)

/kind bug

**Comment by munnerz** [comment]
Seems like a minikube or kubernetes flake, based on `volumes=[shared config elasticsearch-data es-test-token-d6xl6]; skipping pod`.

It failed to even mount the service account secret into the pod. FWIW, we don't use PVs during tests (emptyDir is used).

I'm going to close this now as I don't think it is a bug in Navigator. Feel free to follow up and reopen if you disagree.

/close
