### ISSUE TITLE
Pilot init container resource limits

### ISSUE THREAD

**Issue by cehoffman** [jetstack/navigator#280]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

Init containers to install the pilot into the database container should have resource limits specified too to operate inside of quota enforced namespaces.

**Comment by wallrj** [comment]
In https://github.com/wallrj/navigator/commit/bed5173f47aec3a50520b60afa374e87feb01236#r28074128 @cehoffman  wrote:
> This is only enforcing that requests are set. We have quota set to have caps on limits as well. https://kubernetes.io/docs/concepts/policy/resource-quotas/

Thanks Chris, so we need to add limits *and* requests on the Init container. Sorry I missed that. I was concentrating only on allowing configuration of main pod resources. 
I'll try and test and fix that tomorrow.
