### ISSUE TITLE
Cassandra nodetool tests fail to compile with Go 1.8.x

### ISSUE THREAD

**Issue by wallrj** [jetstack/navigator#300]
```
richard@pet-instance-1:~/go/src/github.com/jetstack/navigator$ go test ./pkg/cassandra/nodetool/...
# github.com/jetstack/navigator/pkg/cassandra/nodetool_test
pkg/cassandra/nodetool/nodetool_test.go:336: ts.Client undefined (type *httptest.Server has no field or method Client)
FAIL    github.com/jetstack/navigator/pkg/cassandra/nodetool [build failed]
?       github.com/jetstack/navigator/pkg/cassandra/nodetool/client     [no test files]
?       github.com/jetstack/navigator/pkg/cassandra/nodetool/fake       [no test files]
richard@pet-instance-1:~/go/src/github.com/jetstack/navigator$ go version
go version go1.8.3 linux/amd64

```

Not sure if we need to fix this.
Perhaps we should just document that we only support Navigator compiled with Go 1.9+

/kind bug

Noticed this while running `make test` from #242

**Comment by munnerz** [comment]
I'm happy to accept that you need Go 1.9+ to build, otherwise we're locking ourselves out of new features in the stdlib to support old and unused (by us) Go versions.

This is also only in tests, and it'd still be possible to build navigator itself with 1.8 anyway.

/close
