### ISSUE TITLE
All log messages have the prefix "ERROR: logging before flag.Parse"

### ISSUE THREAD

**Issue by wallrj** [jetstack/navigator#73]
E.g.

```
ERROR: logging before flag.Parse: I1031 09:43:01.178940       1 round_trippers.go:442] Response Headers:
ERROR: logging before flag.Parse: I1031 09:43:01.178954       1 round_trippers.go:445]     X-Content-Type-Options: nosniff
ERROR: logging before flag.Parse: I1031 09:43:01.178964       1 round_trippers.go:445]     Content-Length: 122
ERROR: logging before flag.Parse: I1031 09:43:01.179023       1 round_trippers.go:445]     Date: Tue, 31 Oct 2017 09:43:01 GMT
ERROR: logging before flag.Parse: I1031 09:43:01.179034       1 round_trippers.go:445]     Content-Type: text/plain
ERROR: logging before flag.Parse: I1031 09:43:01.179332       1 request.go:836] Response Body: User "system:serviceaccount:navigator:navigator-navigator-controller" cannot get endpoints in the namespace "kube-system".

```

/kind bug

Others have had the same problem:
 * https://github.com/kubernetes-incubator/service-catalog/issues/1187

Solution seems to be either to pin glog to a version prior to the introduction of the check:
 * https://github.com/kubernetes-incubator/service-catalog/pull/1204

Or to call `goflag.CommandLine.Parse([]string{})`....somewhere:
 * https://github.com/kubernetes/kubernetes/issues/17162#issuecomment-225596212

**Comment by munnerz** [comment]
Yep, there's another example of the fix for this in cert-manager. https://github.com/jetstack-experimental/cert-manager/blob/master/cmd/controller/main.go#L35
