### ISSUE TITLE
Support ElasticsearchCluster scale down

### ISSUE THREAD

**Issue by munnerz** [jetstack/navigator#98]
/kind feature

We should support scaling down Elasticsearch clusters. A rough flow:

- User scales down a node pool by changing replica count from 3->2
- Navigator observes this change, and must determine *which* Pilot should be taken out of service.
    * this could be influenced by the underlying 'controller' being used by Navigator (i.e. if the ES cluster nodes are created with a StatefulSet (which they always are in the case of Elasticsearch right now), it's always the highest ordinal node that will be decommissioned)
    * if in future there's a way for us to more closely control the process of selecting a node, it may be influenced by some application metric.
- Navigator marks the chosen Pilot as 'decommissioned'
- The leader elected Pilot (ref #97) then sets the `exclude shards` to include the Pilot in question
- The Pilot that is being scaled down should periodically update it's own status block with the remaining shards (this should happen anyway as part of a standard ES Pilot 'sync', periodically)
- Once the number of shards on that Pilot is 0, Navigator should then actually scale down the cluster
- Once the leader elected Pilot see's that the Pilot has been deleted (or the 'decommissioned' state has been set to false), it will remove it from the shard exclusion parameter.

**Comment by wallrj** [comment]
Fixed in https://github.com/jetstack/navigator/pull/241
